@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmQyMzgxNDFhZWUxMTExOWM1NzAyNjEiLCJpYXQiOjE2MDc2NjQ0NzEsImV4cCI6MTYwNzcyOTI3MX0.RcD1qjb85P5ZmywYPplCBDyU-lRKtoZcqJADxk8lWkc

### get activity 
GET {{host}}/activity/5fd31a0aeba1a2073c5df8b5/?skip=0
Authorization: {{token}}

