@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmNlZmMwYmEyMGFjYzJiZDQ2NTZjMjQiLCJpYXQiOjE2MDc0MDA0NjEsImV4cCI6MTYwNzQ2NTI2MX0.bfjOUFF8MfS99MVlbi6DaHrsA-qY2gFHqPwUPUtrjTY

### get boards 
GET {{host}}/board/boards
Authorization: {{token}}

### get board by id
GET {{host}}/board/5fcefdc3a20acc2bd4656c25
Authorization: {{token}}

### get members by id
GET {{host}}/board/members/5fcefdc3a20acc2bd4656c25
Authorization: {{token}}

### create new board
POST {{host}}/board
Authorization: {{token}}
Content-Type: application/json

{
    "boardName" : "fff", 
    "catagery" : "Education",
    "bg": {
        "isColour" : "true",
        "name" : "rgb(82 , 157, 52)"
    }   
}

### update public appearence
PUT {{host}}/board/public
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fc1f3f61e617c558021e542", 
    "isPublic" : "true"   
}

### add new status
PUT {{host}}/board/add-status
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fbcf3f378cea02890c51004", 
    "status" : "Doing"
}

### delete the status
PUT {{host}}/board/del-status
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fbcd738a4ebe51774835d50", 
    "status" : "Doing"
}

### reorder-task
PUT {{host}}/board/reorder-task
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fbcd738a4ebe51774835d50", 
    "status" : "To-do",
    "taskId" : "5fbcdb3395937d27e08afc0b",
    "to" : 0
}

### restatus-task
PUT {{host}}/board/restatus-task
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fbcd738a4ebe51774835d50", 
    "fromStatus" : "To-do",
    "toStatus" : "Done",
    "taskId" : "5fbcdb4195937d27e08afc0d",
    "to" : 0
}

### reorder-status
PUT {{host}}/board/reorder-status
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fbcd738a4ebe51774835d50", 
    "from" : 3,
    "to" : 0
}

### add member to the board
PUT {{host}}/board/addmember
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fcefdc3a20acc2bd4656c25", 
    "memId" : "5fc9b6616c2d364d00551e7b",
    "permision": "Admin"
}

### remove member from the board
PUT {{host}}/board/removememb
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fab59917b56184058ac519e", 
    "_id" : "5fab59f57b56184058ac519f"   
}

### delete the board
DELETE {{host}}/board/5fc1f1419fec761808c236d7
Authorization: {{token}}
