@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmFlNGJmMzAxMThhNTFiMzBlYTc0ZGMiLCJpYXQiOjE2MDUyNTgyMzIsImV4cCI6MTYwNTMyMzAzMn0.CIE6Y1XL7yxmkX_g3n8e4WLUO2NS_EoUAHgcn5DP3lc

### get boards 
GET {{host}}/board/boards
Authorization: {{token}}

### get board by id
GET {{host}}/board/5fae4cc30118a51b30ea74e1
Authorization: {{token}}

### get members by id
GET {{host}}/board/members/5fae4cc30118a51b30ea74e1
Authorization: {{token}}

### create new board
POST {{host}}/board
Authorization: {{token}}
Content-Type: application/json

{
    "boardName" : "nbbbgvvfc", 
    "catagery" : "Others"   
}

### update public appearence
PUT {{host}}/board/public
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fae4ddc0118a51b30ea74e3", 
    "isPublic" : "true"   
}

### add member to the board
PUT {{host}}/board/addmember
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fae4ddc0118a51b30ea74e3", 
    "memId" : "5fae4c220118a51b30ea74dd"
}

### remove member from the board
PUT {{host}}/board/removememb
Authorization: {{token}}
Content-Type: application/json

{
    "boardId" : "5fab59917b56184058ac519e", 
    "_id" : "5fab59f57b56184058ac519f"   
}

### delete the board
DELETE {{host}}/board/5fa8e58d89686809904c85ec
Authorization: {{token}}
