@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmM5ZTNkYzk1ZWUzNjQxZDRkNjRlNGEiLCJpYXQiOjE2MDczMTQ1ODUsImV4cCI6MTYwNzM3OTM4NX0.BDwA6NMJXck-yWqgf-siPb1gvSQUWX7WIpR3dQn2jEo

### get room details
GEt {{host}}/room/5fc9e4e095ee3641d4d64e4f
Authorization: {{token}}

### create room admin
POST {{host}}/room/create
Authorization: {{token}}
Content-Type: application/json

{
    "boardId":"5fc9e42095eeee3641d4de4b",
    "room":"nnjnh",
    "pass":"pass"
}

### join in the room 
POST {{host}}/room/join
Authorization: {{token}}
Content-Type: application/json

{
    "room":"nnjnh",
    "pass":"pass"
}

### delete the room
DELETE {{host}}/room/5fc884b6944b1f15047ff582
Authorization: {{token}}
