@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmIyNzcxMzMxYzc3NjIwNmM1MWU3ZTAiLCJpYXQiOjE2MDU1MzE0MTcsImV4cCI6MTYwNTU5NjIxN30.FPHI1xmfXUmBttsd5P9s0YVmgo1LfEMe2f_91V6AgWk

### get shared
GET {{host}}/shared/boards/?skip=0
Authorization: {{token}}

### get public boards 
GET {{host}}/shared/public/?skip=0
Authorization: {{token}}

### get shared board by id
GET {{host}}/shared/5fb2767231c776206c51e7da
Authorization: {{token}}
