@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmM5YjY2MTZjMmQzNjRkMDA1NTFlN2IiLCJpYXQiOjE2MDc0MDA5NzUsImV4cCI6MTYwNzQ2NTc3NX0._54JfJFo1CEKGUsRCbYwQ0HJe0sjyAZ8cXRqSmVD0j4

### get shared
GET {{host}}/shared/boards/?skip=0
Authorization: {{token}}

### get public boards 
GET {{host}}/shared/public/?skip=0
Authorization: {{token}}
