@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmFiNTc5NTU0YTYzYjQ0NDAxMDAwYWMiLCJpYXQiOjE2MDUwNjQ2MTIsImV4cCI6MTYwNTEyOTQxMn0.l_5UhWVh4KVNLqucN2gCVelZ-1MX4wd41gcZx_6sHuc

### get tasks of board 
GET {{host}}/task/5fab59917b56184058ac519e
Authorization: {{token}}

### get task by id 
GET {{host}}/task/task/5fab63fabd7b174b5c2d689a
Authorization: {{token}}

### create a task
POST {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "title": "oomknluo",
    "status": "Doing",
    "boardid" : "5fab7c8fcfba304f2ca50eba"
}

### update task 
PUT {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "taskId": "5fab63fabd7b174b5c2d689a",
    "body" : "bbbb nnnn",
    "status": "To-do",
    "title": "jhub"
}

### for above use status, body, title to update

### delete the tasks
DELETE {{host}}/task/5fa8e58d89686809904c85ec/5fa8ea6982cbf735a80325c8
Authorization: {{token}}
