@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmM5ZTNkYzk1ZWUzNjQxZDRkNjRlNGEiLCJpYXQiOjE2MDczMTQ1ODUsImV4cCI6MTYwNzM3OTM4NX0.BDwA6NMJXck-yWqgf-siPb1gvSQUWX7WIpR3dQn2jEo

### get a task
GET {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "taskId" : "5fc1f217ec9c885d984ab15b"
}

### create a task
POST {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "title": "xxd vgrf bbgv bbb",
    "status": "To-do",
    "boardId" : "5fc1fd71ed95933e0c9f67af"
}

### update task 
# optionals : { title, body, (fromStatus && toStatus) }
PUT {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "taskId": "5fc1f40e1e617c558021e546",
    "body": "xbhgvvx",
    "title": "wmkns",
    "fromStatus":"Done", 
    "toStatus": "To-do"
}

### delete the tasks
DELETE {{host}}/task/5fc1ded8497d0c4f14b894fc/5fc1eb83c6e52e63d46855f8/Done
Authorization: {{token}}
