@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmQyMzgxNDFhZWUxMTExOWM1NzAyNjEiLCJpYXQiOjE2MDc2NjQ0NzEsImV4cCI6MTYwNzcyOTI3MX0.RcD1qjb85P5ZmywYPplCBDyU-lRKtoZcqJADxk8lWkc

### get a task
GET {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "taskId" : "5fd31c2a591f2e10205b0489"
}

### create a task
POST {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "title": "nn bhgvb nn nj",
    "status": "Doing",
    "boardId" : "5fd31a0aeba1a2073c5df8b5"
}

### update task 
# optionals : { title, body, (fromStatus && toStatus) }
PUT {{host}}/task
Content-Type: application/json
Authorization: {{token}}

{
    "taskId": "5fd255e5c70c392fa05c24b0",
    "fromStatus":"Doing", 
    "toStatus": "Done"
}

### delete the tasks
DELETE {{host}}/task/5fc1ded8497d0c4f14b894fc/5fc1eb83c6e52e63d46855f8/Done
Authorization: {{token}}
