@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmM5YjY2MTZjMmQzNjRkMDA1NTFlN2IiLCJpYXQiOjE2MDc0MDA5NzUsImV4cCI6MTYwNzQ2NTc3NX0._54JfJFo1CEKGUsRCbYwQ0HJe0sjyAZ8cXRqSmVD0j4

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmIyNzcxMzMxYzc3NjIwNmM1MWU3ZTAiLCJpYXQiOjE2MDU1MzE0MTcsImV4cCI6MTYwNTU5NjIxN30.FPHI1xmfXUmBttsd5P9s0YVmgo1LfEMe2f_91V6AgWk
### rrr@gmail.com, rrrr, 5fb2771331c776206c51e7e0

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmMyMTk2NTIwY2FjNjU3OTRjMzIwMjQiLCJpYXQiOjE2MDY1NTYwMDcsImV4cCI6MTYwNjYyMDgwN30.McShtd-huIdskzPqEqluHG3jWPhXN50mr6vBixH_EtE
### yyy@gmail.com, yyy, 5fc2196520cac65794c32024

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmMxZTlmMGM2ZTUyZTYzZDQ2ODU1ZjMiLCJpYXQiOjE2MDY1NDM4NjYsImV4cCI6MTYwNjYwODY2Nn0.CM6alBQdg4SzfrswYrfIZYIH-Wt3uaFPrKNwuR7NiMM
### hhh@gmail.com, hhhh, 5fc1e9f0c6e52e63d46855f3

### get me 
GET {{host}}/user/me
Authorization: {{token}}

### register
POST {{host}}/user/register
Content-Type: application/json

{
    "userName": "tgg",
    "email" : "tff@gmail.com",
    "password" : "aA1!aa"
}

### login
POST {{host}}/user/login
Content-Type: application/json

{
    "email" : "hhh@gmail.com",
    "password" : "aA1!aa"
}

### search user
POST {{host}}/user/search
Content-Type: application/json
Authorization: {{token}}

{
    "query": "aaaa"
}

### logout
POST {{host}}/user/logout
Content-Type: application/json
Authorization: {{token}}