@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmIyNzNmMzMzMTY1ZTA4MTg0NmQzODkiLCJpYXQiOjE2MDU1MzA2MTYsImV4cCI6MTYwNTU5NTQxNn0.b-8UpuwZCfZiTjShqn2E161Fd17B04C_haEB4kEpcUQ

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmIyNzcxMzMxYzc3NjIwNmM1MWU3ZTAiLCJpYXQiOjE2MDU1MzE0MTcsImV4cCI6MTYwNTU5NjIxN30.FPHI1xmfXUmBttsd5P9s0YVmgo1LfEMe2f_91V6AgWk
### rrr@gmail.com, rrrr, 5fb2771331c776206c51e7e0

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmFlNGMyMjAxMThhNTFiMzBlYTc0ZGQiLCJpYXQiOjE2MDUyNTgyODEsImV4cCI6MTYwNTMyMzA4MX0._B02X0d_5dyo8vL1ozhoIEkjg6lQ3bziTI1fHMBjgpY
### ccc@gmail.com, cccc, 5fae4c220118a51b30ea74dd

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmIyNzNmMzMzMTY1ZTA4MTg0NmQzODkiLCJpYXQiOjE2MDU1MzA2MTYsImV4cCI6MTYwNTU5NTQxNn0.b-8UpuwZCfZiTjShqn2E161Fd17B04C_haEB4kEpcUQ
### ddd@gmail.com, dddd, 5fb273f333165e081846d389

### get me 
GET {{host}}/user/me
Authorization: {{token}}

### register
POST {{host}}/user/register
Content-Type: application/json

{
    "userName": "rrrr",
    "email" : "rrr@gmail.com",
    "password" : "aA1!aa"
}

### login
POST {{host}}/user/login
Content-Type: application/json

{
    "email" : "rrr@gmail.com",
    "password" : "aA1!aa"
}

### search user
POST {{host}}/user/search
Content-Type: application/json
Authorization: {{token}}

{
    "query": "aaaa"
}

### logout
POST {{host}}/user/logout
Content-Type: application/json
Authorization: {{token}}